### PR TITLE
Add administrator contact to contribution section

### PR DESCRIPTION
**Pull request by JeremD**

### CODE REVIEW

**Comment by JeremD** [comment]
@tcheymol

**Comment by williamdclt** [comment]
There's only one administrator and it *has* to be approved by him? Not sure it's a good idea. Has this been discussed?

**Comment by JeremD** [comment]
I discussed this quickly with Thibaut, if it is not this process, there has to be one :)

**Comment by benja-M-1** [comment]
@JeremD très bien :) Merci !

**Pull request merged**
